import { useMemo, useState } from 'react'
import type { Goal, GoalHorizon, LifeDomain, PlanTask, SelfProfile, TaskPriority } from '../../types/self'
import { LIFE_DOMAIN_LABELS } from '../../types/self'
import { loadApiKey, loadModel } from '../../lib/storage'
import {
  addCompletionReflection,
  addGoal,
  addMilestone,
  addPlanTask,
  completePlanTask,
  dateKey,
  deletePlanTask,
  nextDate,
  plannerOf,
  postponePlanTask,
  PRIORITY_LABELS,
  reopenPlanTask,
  tasksForDate,
  weekDates,
} from '../../lib/plannerStore'
import { buildFallbackPlanSuggestion, DOMAIN_LABELS, suggestPlanWithGemini, type PlanSuggestion } from '../../lib/planSuggestionEngine'
import { Button } from '../ui'

type Tab = 'today' | 'week' | 'goals'
const horizons: { id: GoalHorizon; label: string }[] = [
  { id: 'month', label: '이번 달' }, { id: 'quarter', label: '3개월' }, { id: 'half_year', label: '6개월' }, { id: 'year', label: '1년' }, { id: 'custom', label: '직접 정하기' },
]
const priorities: TaskPriority[] = ['must', 'should', 'could']

function dateLabel(date: string) {
  return new Date(`${date}T12:00:00`).toLocaleDateString('ko-KR', { month: 'numeric', day: 'numeric', weekday: 'short' })
}

function horizonDate(horizon: GoalHorizon, start: string): string {
  const d = new Date(`${start}T12:00:00`)
  const months: Record<GoalHorizon, number> = { week: 0, month: 1, quarter: 3, half_year: 6, year: 12, custom: 0 }
  if (horizon === 'week') d.setDate(d.getDate() + 7)
  else d.setMonth(d.getMonth() + months[horizon])
  return dateKey(d)
}

function TaskRow({ task, onDone, onReopen, onPostpone, onDelete }: { task: PlanTask; onDone: () => void; onReopen: () => void; onPostpone: () => void; onDelete: () => void }) {
  return <div className="rounded-xl border border-border/70 bg-surface-2/70 px-3 py-3 flex gap-2.5 items-start">
    <button type="button" onClick={task.status === 'done' ? onReopen : onDone} className={`mt-0.5 w-5 h-5 shrink-0 rounded-full border-2 text-[11px] flex items-center justify-center ${task.status === 'done' ? 'border-accent bg-accent text-surface' : 'border-muted/60 text-transparent'}`} aria-label={task.status === 'done' ? '완료 해제' : '완료'}>✓</button>
    <div className="min-w-0 flex-1"><p className={`text-sm leading-snug ${task.status === 'done' ? 'line-through text-muted' : 'text-ink'}`}>{task.title}</p><p className="text-[11px] text-muted mt-1">{PRIORITY_LABELS[task.priority]}{task.estimatedMinutes ? ` · ${task.estimatedMinutes}분` : ''}</p></div>
    {task.status !== 'done' && <button type="button" onClick={onPostpone} className="text-[11px] text-muted hover:text-accent px-1">내일</button>}
    <button type="button" onClick={onDelete} className="text-[11px] text-muted hover:text-status-error px-1" aria-label="할 일 삭제">✕</button>
  </div>
}

function CompletionSheet({ task, profile, onSave, onSkip }: { task: PlanTask; profile: SelfProfile; onSave: (emotion: string, pride: string, learning: string, futureCloseness: string) => void; onSkip: () => void }) {
  const [emotion, setEmotion] = useState('뿌듯해')
  const [pride, setPride] = useState('')
  const [learning, setLearning] = useState('')
  const [futureCloseness, setFutureCloseness] = useState('')
  return <div className="fixed inset-0 z-50 bg-void/50 backdrop-blur-sm flex items-end sm:items-center justify-center p-3"><div className="w-full max-w-md rounded-3xl bg-surface border border-border shadow-xl p-5 space-y-4 animate-fade-up"><div><p className="text-[11px] text-accent font-medium">해낸 직후의 나를 남겨두자</p><h2 className="text-lg font-semibold text-ink mt-1">{task.title}</h2><p className="text-xs text-muted mt-1">완료는 충분해. 기록은 10초만 써도 돼.</p></div><div className="flex flex-wrap gap-2">{['뿌듯해', '안도돼', '지쳤어', '덤덤해'].map((x) => <button key={x} type="button" onClick={() => setEmotion(x)} className={`px-3 py-1.5 rounded-full text-xs border ${emotion === x ? 'bg-accent/15 text-accent border-accent/40' : 'border-border text-muted'}`}>{x}</button>)}</div><textarea value={pride} onChange={(e) => setPride(e.target.value)} placeholder="오늘 해낸 점 한 줄 (선택)" rows={2} className="w-full rounded-xl border border-border bg-surface-2/60 p-3 text-sm resize-none focus:outline-none focus:border-accent/50"/><textarea value={learning} onChange={(e) => setLearning(e.target.value)} placeholder="다음에도 가져갈 점 (선택)" rows={2} className="w-full rounded-xl border border-border bg-surface-2/60 p-3 text-sm resize-none focus:outline-none focus:border-accent/50"/><textarea value={futureCloseness} onChange={(e) => setFutureCloseness(e.target.value)} placeholder={`이 일로 5년 뒤 ${profile.name || '나'}에게 어떻게 가까워졌나? (선택)`} rows={2} className="w-full rounded-xl border border-border bg-surface-2/60 p-3 text-sm resize-none focus:outline-none focus:border-accent/50"/><div className="flex gap-2 justify-end"><Button variant="ghost" size="sm" onClick={onSkip}>건너뛰기</Button><Button size="sm" onClick={() => onSave(emotion, pride, learning, futureCloseness)}>기록하기</Button></div></div></div>
}

export function PlannerScreen({ profile, onBack, onProfileUpdate, onAskFuture }: { profile: SelfProfile; onBack: () => void; onProfileUpdate: (p: SelfProfile) => void; onAskFuture: (prompt: string) => void }) {
  const [tab, setTab] = useState<Tab>('today')
  const [showGoalForm, setShowGoalForm] = useState(false)
  const [showTaskForm, setShowTaskForm] = useState(false)
  const [reflectionTask, setReflectionTask] = useState<PlanTask | null>(null)
  const [selectedGoalId, setSelectedGoalId] = useState<string>('')
  const [suggestion, setSuggestion] = useState<PlanSuggestion | null>(null)
  const [selectedSuggestionTasks, setSelectedSuggestionTasks] = useState<Set<number>>(() => new Set())
  const [suggesting, setSuggesting] = useState(false)
  const [suggestionError, setSuggestionError] = useState<string | null>(null)
  const today = dateKey()
  const planner = plannerOf(profile)
  const activeGoals = planner.goals.filter((g) => g.status === 'active')
  const todayTasks = tasksForDate(profile, today)
  const week = weekDates()
  const doneCount = todayTasks.filter((t) => t.status === 'done').length
  const [goalDraft, setGoalDraft] = useState({ title: '', purpose: '', desiredOutcome: '', futureConnection: '', domain: 'growth' as LifeDomain, horizon: 'half_year' as GoalHorizon, targetDate: horizonDate('half_year', today) })
  const [taskDraft, setTaskDraft] = useState({ title: '', goalId: '', scheduledFor: today, estimatedMinutes: 30, priority: 'should' as TaskPriority })
  const goalById = useMemo(() => new Map(planner.goals.map((g) => [g.id, g])), [planner.goals])

  const saveGoal = () => { const next = addGoal(profile, { ...goalDraft, startDate: today }); if (next !== profile) { onProfileUpdate(next); setShowGoalForm(false); setGoalDraft({ title: '', purpose: '', desiredOutcome: '', futureConnection: '', domain: 'growth', horizon: 'half_year', targetDate: horizonDate('half_year', today) }) } }
  const saveTask = () => { const next = addPlanTask(profile, { ...taskDraft, goalId: taskDraft.goalId || undefined }); if (next !== profile) { onProfileUpdate(next); setShowTaskForm(false); setTaskDraft({ title: '', goalId: '', scheduledFor: today, estimatedMinutes: 30, priority: 'should' }) } }
  const complete = (task: PlanTask) => { onProfileUpdate(completePlanTask(profile, task.id)); setReflectionTask(task) }
  const askSuggestion = async (goal: Goal) => { setSelectedGoalId(goal.id); setSuggestionError(null); setSuggesting(true); try { const value = await suggestPlanWithGemini(profile, goal, loadApiKey() ?? '', today, loadModel() ?? undefined); setSuggestion(value); setSelectedSuggestionTasks(new Set(value.tasks.map((_, i) => i))) } catch { const value = buildFallbackPlanSuggestion(goal, today); setSuggestion(value); setSelectedSuggestionTasks(new Set(value.tasks.map((_, i) => i))); setSuggestionError('AI 연결이 안 돼서 기본 초안을 보여줘요.') } finally { setSuggesting(false) } }
  const applySuggestion = () => { const goal = goalById.get(selectedGoalId); if (!goal || !suggestion) return; let next = profile; for (const m of suggestion.milestones) next = addMilestone(next, { goalId: goal.id, title: m.title, targetDate: m.targetDate }); for (const [i, t] of suggestion.tasks.entries()) if (selectedSuggestionTasks.has(i)) next = addPlanTask(next, { title: t.title, goalId: goal.id, scheduledFor: t.scheduledFor, estimatedMinutes: t.estimatedMinutes, priority: t.priority }); onProfileUpdate(next); setSuggestion(null) }

  return <div className="h-full max-w-lg mx-auto flex flex-col bg-void"><header className="px-5 py-4 bg-surface border-b border-border flex items-center justify-between"><div><p className="text-[11px] text-accent font-medium">미래의 나에게 가까워지는 오늘</p><h1 className="text-lg font-semibold text-ink">내 플래너</h1></div><button type="button" onClick={onBack} className="text-sm text-muted hover:text-ink">← 대화</button></header><nav className="grid grid-cols-3 gap-1 p-2 bg-surface border-b border-border/60">{([['today','오늘'],['week','이번 주'],['goals','목표']] as const).map(([id,label]) => <button key={id} type="button" onClick={() => setTab(id)} className={`py-2 rounded-xl text-sm ${tab === id ? 'bg-accent/12 text-accent font-medium' : 'text-muted hover:bg-ink/5'}`}>{label}</button>)}</nav><main className="flex-1 overflow-y-auto p-4 space-y-4">
    {tab === 'today' && <><section className="rounded-2xl p-4 border border-accent/25 bg-gradient-to-br from-accent/10 to-surface"><p className="text-xs text-muted">{dateLabel(today)}</p><h2 className="text-xl font-semibold text-ink mt-1">오늘 {doneCount}/{todayTasks.length}개 해냈어</h2><p className="text-sm text-ink/75 mt-2">계획을 다 지키는 날보다, 다시 돌아오는 날이 더 중요해.</p></section><div className="flex gap-2"><Button size="sm" className="flex-1" onClick={() => setShowTaskForm(true)}>+ 오늘 할 일</Button><Button size="sm" variant="secondary" className="flex-1" onClick={() => setShowGoalForm(true)}>+ 목표</Button></div><section className="space-y-2">{todayTasks.length ? todayTasks.map((task) => <TaskRow key={task.id} task={task} onDone={() => complete(task)} onReopen={() => onProfileUpdate(reopenPlanTask(profile, task.id))} onPostpone={() => onProfileUpdate(postponePlanTask(profile, task.id, nextDate(today, 1)))} onDelete={() => onProfileUpdate(deletePlanTask(profile, task.id))}/>) : <div className="text-center rounded-2xl border border-dashed border-border p-7 text-sm text-muted">오늘을 가볍게 시작해봐.<br/>할 일 하나면 충분해.</div>}</section>{activeGoals.length > 0 && <section className="rounded-2xl border border-glow/35 bg-glow/10 p-4"><p className="text-xs text-muted">5년 뒤의 나와 연결</p><p className="text-sm text-ink mt-1">“{activeGoals[0].title}” 때문에 지금 뭘 하면 좋을지 물어볼래?</p><button type="button" onClick={() => onAskFuture(`내 목표 '${activeGoals[0].title}' 때문에 오늘 무엇에 집중하면 좋을까? 너무 거창하지 않게 말해줘.`)} className="mt-3 text-sm text-accent font-medium">미래의 나에게 물어보기 →</button></section>}</>}
    {tab === 'week' && <><div className="flex items-center justify-between"><div><p className="text-xs text-muted">이번 주</p><h2 className="text-lg font-semibold">작게 잡고, 끝까지 보기</h2></div><Button size="sm" onClick={() => setShowTaskForm(true)}>+ 할 일</Button></div>{week.map((day) => { const list = tasksForDate(profile, day); return <section key={day} className="rounded-2xl border border-border bg-surface/70 p-3 space-y-2"><p className={`text-xs font-medium ${day === today ? 'text-accent' : 'text-muted'}`}>{dateLabel(day)}{day === today ? ' · 오늘' : ''}</p>{list.length ? list.map((task) => <TaskRow key={task.id} task={task} onDone={() => complete(task)} onReopen={() => onProfileUpdate(reopenPlanTask(profile, task.id))} onPostpone={() => onProfileUpdate(postponePlanTask(profile, task.id, nextDate(day, 1)))} onDelete={() => onProfileUpdate(deletePlanTask(profile, task.id))}/>) : <p className="text-xs text-muted/70 py-1">비워둔 날</p>}</section> })}</>}
    {tab === 'goals' && <><div className="flex items-center justify-between"><div><p className="text-xs text-muted">장기 목표를 이번 주로</p><h2 className="text-lg font-semibold">내가 가고 싶은 방향</h2></div><Button size="sm" onClick={() => setShowGoalForm(true)}>+ 목표</Button></div>{activeGoals.length ? activeGoals.map((goal) => { const related = planner.tasks.filter((t) => t.goalId === goal.id); const done = related.filter((t) => t.status === 'done').length; return <article key={goal.id} className="rounded-2xl border border-border bg-surface p-4 space-y-3"><div><p className="text-[11px] text-accent">{LIFE_DOMAIN_LABELS[goal.domain]} · {goal.targetDate}까지</p><h3 className="text-base font-semibold text-ink mt-1">{goal.title}</h3>{goal.purpose && <p className="text-sm text-ink/75 mt-2">왜: {goal.purpose}</p>}{goal.futureConnection && <p className="text-xs text-muted mt-1">5년 뒤의 나와: {goal.futureConnection}</p>}</div><p className="text-xs text-muted">연결된 행동 {done}/{related.length} 완료</p><div className="flex gap-2"><Button size="sm" variant="secondary" onClick={() => { setTaskDraft((d) => ({ ...d, goalId: goal.id })); setShowTaskForm(true) }}>행동 추가</Button><Button size="sm" onClick={() => void askSuggestion(goal)} disabled={suggesting}>{suggesting && selectedGoalId === goal.id ? '생각 중…' : 'AI 초안'}</Button></div></article> }) : <div className="text-center rounded-2xl border border-dashed border-border p-8 text-sm text-muted">6개월 후, 1년 후의 목표를 하나 적어봐.<br/>그다음 이번 주 행동으로 같이 나눌게.</div>}</>}
  </main>
  {showGoalForm && <div className="fixed inset-0 z-40 bg-void/50 backdrop-blur-sm overflow-y-auto"><div className="min-h-full max-w-lg mx-auto bg-surface p-5 space-y-4 animate-fade-up"><div className="flex justify-between items-center"><h2 className="text-lg font-semibold">구체적인 목표 만들기</h2><button type="button" onClick={() => setShowGoalForm(false)} className="text-muted">✕</button></div><p className="text-sm text-muted">목표를 잘 세우려면 제목보다 ‘왜’와 ‘어떤 상태’를 먼저 잡는 게 좋아.</p><input value={goalDraft.title} onChange={(e) => setGoalDraft({ ...goalDraft, title: e.target.value })} placeholder="무엇을 이루고 싶어? *" className="w-full rounded-xl border border-border p-3 text-sm"/><textarea value={goalDraft.purpose} onChange={(e) => setGoalDraft({ ...goalDraft, purpose: e.target.value })} placeholder="왜 이걸 이루고 싶어? *" rows={3} className="w-full rounded-xl border border-border p-3 text-sm resize-none"/><textarea value={goalDraft.desiredOutcome} onChange={(e) => setGoalDraft({ ...goalDraft, desiredOutcome: e.target.value })} placeholder="이뤘을 때 어떤 모습이면 충분해? *" rows={3} className="w-full rounded-xl border border-border p-3 text-sm resize-none"/><textarea value={goalDraft.futureConnection} onChange={(e) => setGoalDraft({ ...goalDraft, futureConnection: e.target.value })} placeholder="이 목표가 5년 뒤의 나와 어떻게 이어져? (선택)" rows={2} className="w-full rounded-xl border border-border p-3 text-sm resize-none"/><div className="grid grid-cols-2 gap-2"><select value={goalDraft.domain} onChange={(e) => setGoalDraft({ ...goalDraft, domain: e.target.value as LifeDomain })} className="rounded-xl border border-border p-3 text-sm">{Object.entries(DOMAIN_LABELS).map(([id,label]) => <option key={id} value={id}>{label}</option>)}</select><select value={goalDraft.horizon} onChange={(e) => { const h = e.target.value as GoalHorizon; setGoalDraft({ ...goalDraft, horizon: h, targetDate: h === 'custom' ? goalDraft.targetDate : horizonDate(h, today) }) }} className="rounded-xl border border-border p-3 text-sm">{horizons.map((h) => <option key={h.id} value={h.id}>{h.label}</option>)}</select></div><label className="block text-xs text-muted">목표 날짜<input type="date" value={goalDraft.targetDate} onChange={(e) => setGoalDraft({ ...goalDraft, targetDate: e.target.value })} className="block mt-1 w-full rounded-xl border border-border p-3 text-sm text-ink"/></label><Button className="w-full" onClick={saveGoal} disabled={!goalDraft.title.trim() || !goalDraft.purpose.trim() || !goalDraft.desiredOutcome.trim() || !goalDraft.targetDate}>목표 저장</Button></div></div>}
  {showTaskForm && <div className="fixed inset-0 z-40 bg-void/50 backdrop-blur-sm flex items-end sm:items-center justify-center p-3"><div className="w-full max-w-md rounded-3xl bg-surface p-5 space-y-3 animate-fade-up"><div className="flex justify-between"><h2 className="text-lg font-semibold">할 일 추가</h2><button type="button" onClick={() => setShowTaskForm(false)} className="text-muted">✕</button></div><input value={taskDraft.title} onChange={(e) => setTaskDraft({ ...taskDraft, title: e.target.value })} placeholder="행동 하나를 구체적으로 적어줘" className="w-full rounded-xl border border-border p-3 text-sm"/><div className="grid grid-cols-2 gap-2"><input type="date" value={taskDraft.scheduledFor} onChange={(e) => setTaskDraft({ ...taskDraft, scheduledFor: e.target.value })} className="rounded-xl border border-border p-3 text-sm"/><select value={taskDraft.priority} onChange={(e) => setTaskDraft({ ...taskDraft, priority: e.target.value as TaskPriority })} className="rounded-xl border border-border p-3 text-sm">{priorities.map((p) => <option key={p} value={p}>{PRIORITY_LABELS[p]}</option>)}</select></div><input type="number" min="5" max="240" value={taskDraft.estimatedMinutes} onChange={(e) => setTaskDraft({ ...taskDraft, estimatedMinutes: Number(e.target.value) || undefined as unknown as number })} placeholder="예상 시간(분)" className="w-full rounded-xl border border-border p-3 text-sm"/><select value={taskDraft.goalId} onChange={(e) => setTaskDraft({ ...taskDraft, goalId: e.target.value })} className="w-full rounded-xl border border-border p-3 text-sm"><option value="">목표에 연결 안 함</option>{activeGoals.map((g) => <option key={g.id} value={g.id}>{g.title}</option>)}</select><Button className="w-full" onClick={saveTask} disabled={!taskDraft.title.trim()}>저장</Button></div></div>}
  {reflectionTask && <CompletionSheet task={reflectionTask} profile={profile} onSkip={() => setReflectionTask(null)} onSave={(emotion, pride, learning, futureCloseness) => { onProfileUpdate(addCompletionReflection(profile, { taskId: reflectionTask.id, goalId: reflectionTask.goalId, emotion, pride, learning, futureCloseness })); setReflectionTask(null) }} />}
  {suggestion && <div className="fixed inset-0 z-50 bg-void/50 backdrop-blur-sm overflow-y-auto"><div className="min-h-full max-w-lg mx-auto bg-surface p-5 space-y-4 animate-fade-up"><div className="flex justify-between"><div><p className="text-xs text-accent">저장 전 초안</p><h2 className="text-lg font-semibold">이번 주 제안</h2></div><button type="button" onClick={() => setSuggestion(null)} className="text-muted">✕</button></div>{suggestionError && <p className="text-xs text-status-warn">{suggestionError}</p>}<p className="text-sm text-ink/85">{suggestion.summary}</p>{suggestion.assumptions.length > 0 && <p className="text-xs text-muted">가정: {suggestion.assumptions.join(' · ')}</p>}<section className="space-y-2"><h3 className="text-sm font-medium">마일스톤</h3>{suggestion.milestones.map((m, i) => <div key={`${m.title}-${i}`} className="rounded-xl bg-surface-2 p-3 text-sm">{m.title} {m.targetDate && <span className="text-xs text-muted">· {m.targetDate}</span>}</div>)}</section><section className="space-y-2"><h3 className="text-sm font-medium">이번 주 행동 <span className="text-xs text-muted font-normal">— 담고 싶은 것만 선택</span></h3>{suggestion.tasks.map((t, i) => { const selected = selectedSuggestionTasks.has(i); return <button key={`${t.title}-${i}`} type="button" onClick={() => setSelectedSuggestionTasks((prev) => { const next = new Set(prev); if (next.has(i)) next.delete(i); else next.add(i); return next })} className={`w-full text-left rounded-xl border p-3 flex gap-2.5 items-start transition-colors ${selected ? 'border-accent/50 bg-accent/8' : 'border-border opacity-60'}`}><span className={`mt-0.5 w-5 h-5 shrink-0 rounded-full border-2 text-[11px] flex items-center justify-center ${selected ? 'border-accent bg-accent text-surface' : 'border-muted/60 text-transparent'}`} aria-hidden>✓</span><span className="min-w-0"><p className="text-sm text-ink">{t.title}</p><p className="text-xs text-muted mt-1">{t.estimatedMinutes ? `${t.estimatedMinutes}분 · ` : ''}{PRIORITY_LABELS[t.priority]} {t.whyNow ? `· ${t.whyNow}` : ''}</p></span></button> })}</section>{suggestion.caution && <p className="text-xs text-muted bg-glow/10 rounded-xl p-3">{suggestion.caution}</p>}<div className="flex gap-2"><Button className="flex-1" variant="secondary" onClick={() => setSuggestion(null)}>다시 생각할게</Button><Button className="flex-1" onClick={applySuggestion} disabled={selectedSuggestionTasks.size === 0}>{selectedSuggestionTasks.size ? `선택한 ${selectedSuggestionTasks.size}개 담기` : '행동을 선택해줘'}</Button></div></div></div>}
  </div>
}
